### ISSUE TITLE
Realize TaskSetup/TaskTeardown 

### ISSUE THREAD

**Issue by borovskyav** [SimpleGitVersion/CodeCake#3]
Hi! Do you have any reasons to not realize TaskSetup and TaskTeardown methods in CodeCakeHost?

**Comment by olivier-spinelli** [comment]
Sorry for this very late answer. I missed your post :(
The answer is that there is absolutely no other reason that the fact that I didn't need them!
This should be quite easy to implement. I have a bit of time right now. I dot it.

**Comment by olivier-spinelli** [comment]
v0.25.0 now implements TaskSetup/TaskTeardown.
